### ISSUE TITLE
The phone can search for the printer, but once you click print, the message "Offline" pops up

### ISSUE THREAD

**Issue by buzai** [thyrlian/AirPdfPrinter#2]
i fin some logs

E [15/May/2020:18:51:39 +0000] Unknown directive BrowseOrder on line 22 of /etc/cups/cupsd.conf.
E [15/May/2020:18:51:39 +0000] Unknown directive BrowseAllow on line 24 of /etc/cups/cupsd.conf.
E [15/May/2020:18:51:39 +0000] Unknown directive BrowseAddress on line 25 of /etc/cups/cupsd.conf.
E [15/May/2020:18:51:39 +0000] Unable to communicate with avahi-daemon: Daemon not running
E [17/Aug/2022:16:58:27 +0000] Unknown directive BrowseOrder on line 22 of /etc/cups/cupsd.conf.
E [17/Aug/2022:16:58:27 +0000] Unknown directive BrowseAllow on line 24 of /etc/cups/cupsd.conf.
E [17/Aug/2022:16:58:27 +0000] Unknown directive BrowseAddress on line 25 of /etc/cups/cupsd.conf.
E [17/Aug/2022:16:58:27 +0000] Unable to open listen socket for address 0.0.0.0:631 - Address already in use.
E [17/Aug/2022:16:58:27 +0000] Unable to communicate with avahi-daemon: Daemon not running

**Comment by thyrlian** [comment]
Hi, I haven't updated anything since the release (and testing).

As you can see from the logs, the above part has the timestamp of 2020, which was the date of release, so they're just warnings, not issues.

> `Unable to open listen socket for address 0.0.0.0:631 - Address already in use.`

You have to check if that port 631 has already been taken

> `Unable to communicate with avahi-daemon: Daemon not running`

If you run the container in the background, the services should be run automatically, according to [this](https://github.com/thyrlian/AirPdfPrinter/blob/master/Dockerfile#L48).  But if you run the container with an interactive shell, you'll have to start CUPS print server on your own, check [the Commands section under HOWTO](https://github.com/thyrlian/AirPdfPrinter#howto).

Last, please be aware, the host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, as stated [here](https://docs.docker.com/network/network-tutorial-host/#prerequisites).

**Comment by buzai** [comment]
@thyrlian awesome, I fixed it.

**Comment by thyrlian** [comment]
Cool, good to hear that you solved the problem.  May you let us know what exactly have you done to get it work?  Thanks.

**Comment by buzai** [comment]
@thyrlian 
rookie mistake, I didn't close the cups service that comes with linux

**Comment by thyrlian** [comment]
Got it, that's why the logs said the port 631 has been taken.  Thank you.
